import React from 'react'
import Head from 'next/head'
import Sidebar from '../components/sidebar/Sidebar'
import TopNav from '../components/topnav/TopNav'


interface P {
    children: React.ReactNode
}

const MainLayout = ({children} : P) => {
    return (
        <>
        <Head>
        <title>Book Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossOrigin="anonymous" />
      <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet' />

    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />

      </Head>

            <Sidebar />
            <div className="main">
                <div className="main__content">
                     <TopNav /> 
                    {children}
                </div>
            </div>
        </>
    )
}

export default MainLayout
